name: ice_cream
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  # Firebase
  firebase_core: ^3.12.0  # Replace with the correct latest version
  firebase_messaging: ^15.2.3

  stacked_shared: any
  intl: any
  barcode_widget: any
  flutter_svg: any
  gap: any
  shared_preferences: any
  fluttertoast: any
  provider: any
  auto_size_text: any
  skeletonizer: any
  http: any
  ZmrzlinaApi:
    version: ^3.1.15
    hosted:
      url: https://dart.cloudsmith.io/techheaven-z-u/lepsidart/
  barcode: ^2.2.9
  mobile_scanner: ^6.0.6
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.28.0
  flutter_localization: ^0.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

  # Other
  flutter_requery: ^0.1.14
  animations: ^2.0.2
  get_it: ^8.0.3
  package_info_plus: ^4.2.0  # Replacing deprecated package_info
  flutter_dotenv: ^5.0.2
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  mask_text_input_formatter: ^2.3.0
  page_transition: ^2.1.0
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^6.0.0
  dart_date: ^1.4.0
  barcode_scanner: ^6.1.1

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
